print('====== EX004 =====')
a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabetico? {}'.format(a.isalpha()))
print('É alfanumerico? {}'.format(a.isalnum()))
print('Está em Maiusculas? '.format(a.isupper()))
print('Está em Minusculas? {}'.format(a.islower()))
print('Está Capitalizada? {}'.format(a.istitle()))
